### ISSUE TITLE
I can appreciate you not wanting to upload the build, however, source files still do not appear to be working

### ISSUE THREAD

**Issue by alexrednaz** [dedouwe26/Cosmetx#11]
I pulled your source files and ran a dotnet build on them which worked successfully.
However the mod still does not work in game with the exported D-library.
Maybe i did not understand the intentions as they were vauge (for good reason)

Should this be working after being ran with .net?

Cosmetx -> Z:\xxxxxxx\yyyyyyyy\zzzzzzzz\aaaaaaaaa\Cosmetx-1.2.2\Cosmetx\bin\Debug\netstandard2.1\Cosmetx.dll

If not i get it and can be closed, if so, i just wanted to mention I do not think it is fixed yet.

**Comment by dedouwe26** [comment]
It seems alright.
Did you get build errors?
Or did you get errors at runtime (in game)? (to see that open the BepInEx console in the config)

**Comment by alexrednaz** [comment]
hmm, no errors on build. checking the console and i see the plugin is loading but I think i see the problem down below this account was banned and that may be stopping the cosmetics from loading onto the pedestal. Will try on another account.

[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Utilla 1.6.13]
[Info   :   BepInEx] Loading [Cosmetx 1.2.1]
[Info   :   Cosmetx] Plugin is enabled

Info   : Unity Log] Original text = 
[Info   : Unity Log] Got steam auth session ticket!
[Info   : Unity Log] Found left controller: OpenVR Controller(Oculus Quest3 (Left Controller)) - Left ControllerType: OCULUS_DEFAULT
[Info   : Unity Log] Microphone: GorillaSpeakerLoudness 0, raw null, permission True, connected True, isSpeaking False, recorder.TransitEnabled = null, IsCurrentlyTransmitting null
[Info   : Unity Log] TitleData fetched: 0.19351
[Info   : Unity Log] OnPlayFabError(): The account making this request is currently banned
[Info   : Unity Log] TitleData fetched: 0.05579
[Info   : Unity Log] StoreUpdater - GetEventsFromTitleData
[Info   : Unity Log] StoreUpdater - Recieved TitleData : [{"PedestalID":"Pedestal1","ItemName":"LBAFB.","StartTimeUTC":"2024-06-01T22:00:00.000Z","EndTimeUTC":"2024-06-02T22:00:00.000Z"},{"PedestalID":"Pedestal1","ItemName":"LBAFO.","StartTimeUTC":"2024-06-02T22:00:00.000Z","EndTimeUTC":"2024-06-03T22:00:00.000Z"}]
[Info   : Unity Log] StoreUpdater - HandleRecievingEventsFromTitleData
[Warning: Unity Log] StoreUpdater - CosmeticsController is not initialized.  Reinitializing TitleData
[Info   : Unity Log] TitleData fetched: 0.06437
[Info   : Unity Log] StoreUpdater - GetEventsFromTitleData
[Info   : Unity Log] StoreUpdater - Recieved TitleData : [{"PedestalID":"Pedestal1","ItemName":"LBAFB.","StartTimeUTC":"2024-06-01T22:00:00.000Z","EndTimeUTC":"2024-06-02T22:00:00.000Z"},{"PedestalID":"Pedestal1","ItemName":"LBAFO.","StartTimeUTC":"2024-06-02T22:00:00.000Z","EndTimeUTC":"2024-06-03T22:00:00.000Z"}]
[Info   : Unity Log] StoreUpdater - HandleRecievingEventsFromTitleData
[Warning: Unity Log] StoreUpdater - CosmeticsController is not initialized.  Reinitializing TitleData
[Info   : Unity Log] TitleData fetched: 0.04748
[Info   : Unity Log] StoreUpdater - GetEventsFromTitleData
[Info   : Unity Log] StoreUpdater - Recieved TitleData : [{"PedestalID":"Pedestal1","ItemName":"LBAFB.","StartTimeUTC":"2024-06-01T22:00:00.000Z","EndTimeUTC":"2024-06-02T22:00:00.000Z"},{"PedestalID":"Pedestal1","ItemName":"LBAFO.","StartTimeUTC":"2024-06-02T22:00:00.000Z","EndTimeUTC":"2024-06-03T22:00:00.000Z"}]
[Info   : Unity Log] StoreUpdater - HandleRecievingEventsFromTitleData
[Warning: Unity Log] StoreUpdater - CosmeticsController is not initialized.  Reinitializing TitleData
[Info   : Unity Log] TitleData fetched: 0.06332

**Comment by alexrednaz** [comment]
Tried on a new account and it works great. Appreciate you uploading the source files and letting ppl enjoy. My son is very happy :D

**Comment by GKVR16** [comment]
hello alex,could i please get the file? im not sure how to create it.

**Comment by SigmaMan69420** [comment]
yeah can you please give us the file i dont know how to build it either

**Comment by GKVR16** [comment]
fr

**Comment by alexrednaz** [comment]
His instructions are pretty clear in the Readme. I challenge you to try to build it yourself and I will add more descriptive and easier to follow instructions below. Plus its never a good idea to take a .dll from a stranger :)

 If Owner wants this deleted please say so. 

- Click on the Latest release on the right side of the page that says 1.2.2 Latest
- Click on Source code (zip) under Assets
- Extract the files you downloaded to your desktop (easier to explain) so you should have a folder on the desktop called Cosmetx-1.2.2
- Open the Cosmetx-1.2.2 folder you extracted and then open the Cosmetx folder. You will see a file called Directory.Build.props  You will need to right click this file and click Open With, and use notepad (or whatever text editor you want).
- on the 4th line You will see a <GamePath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag<GamePath> you will need to replace the path that is there with your path to Gorilla Tag. Make sure you insert your path between the 2 <Gamepath> variables and do not delete or change them. Then save your file when complete.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
- Go to the following website and download the .net 8 SDK for your operating system 8.0.301 is newest.
- https://dotnet.microsoft.com/en-us/download/dotnet/8.0
- Install .net8 on your PC
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
- Open command prompt or power shell and navigate to the directory you extracted the files too. If you extracted to desktop like i said earlier you can type "cd C:\Users\Username\Desktop\Cosmetx-1.2.2" without the "" and change Username to match yours. you should see this on the prompt C:\Users\Username\Desktop\Cosmetx-1.2.2>
- Now type dotnet build and press enter.
- You should see that the build was completed successfully.
- Now navigate to ...\Cosmetx-1.2.2\Cosmetx\bin\Debug\netstandard2.1
- You will see a file called Cosmetx.dll

- If you at least try this and fail, reach out to me on Discord and I can try to help you further. 
Discord Tag: zandered

Again alot of thanks to dedouwe26 for providing the source code to everyone

**Comment by Gorillabobfart** [comment]
I followed the instructions, and I got a bunch of errors so it would be greatly appreciated if you could give me the dll please.

**Comment by GTAGISTHEBESTsigma69402** [comment]
sure but its a zip file u have to extract it with zip or 7z
[Cosmetx.zip](https://github.com/user-attachments/files/15529336/Cosmetx.zip)

**Comment by GTAGISTHEBESTsigma69402** [comment]
im sorry if im not allowed to

**Comment by GKVR16** [comment]
does it cost any money??

**Comment by SigmaMan69420** [comment]
thank you so much it worked the dll file

**Comment by GKVR16** [comment]
yo sigma man can i have it?

**Comment by GKVR16** [comment]
im confused

**Comment by GKVR16** [comment]
i put it under plugins after making the cosmetx file but it still dosnt work inside the game,could anyone assist me.i had followed all the steps mentioned

**Comment by Alexrednazz** [comment]
If you tried and it didn't work reach out to me on Disord, I don't want to keep spamming this guys issues box with troubleshooting steps.
Discord - zandered

**Comment by GKVR16** [comment]
i sent a request.
