### ISSUE TITLE
the file isnt working

### ISSUE THREAD

**Issue by GKVR16** [dedouwe26/Cosmetx#13]
i had made the cosmetx.dll file but i cannot figure out why it is not working in-game.could anyone assist me?

**Comment by dedouwe26** [comment]
Did you get build errors?

**Comment by dedouwe26** [comment]
Hello, did you get any build errors? @GKVR16

**Comment by GKVR16** [comment]
i had fixed it,thank you for trying to help.

**Comment by GKVR16** [comment]
am i allowed to give the file to my friend only? i wont do it if you tell me not to.

**Comment by therealbananaVR** [comment]
Yo GKVR16 do u mind sending me the file. I'd really appreciate that since cosmetx is really important for me.
