### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by iiDk-the-actual** [dedouwe26/Cosmetx#14]
Used it banned / not, I think the build in the source isn't the same as the release, as it was last updated like 3 months ago

**Comment by dedouwe26** [comment]
It probably doesn't work when your banned (because you can't access Playfab).

**Comment by Alexrednazz** [comment]
> Used it banned / not, I think the build in the source isn't the same as the release, as it was last updated like 3 months ago

You need to download it in his releases tab. That is the updated files. He did not update the repo itself.
