### ISSUE TITLE
cant see the dll file

### ISSUE THREAD

**Issue by thecheesman1** [dedouwe26/Cosmetx#17]
so i did the instructions and it doesn't come up

**Comment by thecheesman1** [comment]
idk if im doing it right

**Comment by thecheesman1** [comment]
![image](https://github.com/dedouwe26/Cosmetx/assets/174196056/42c1f136-93c0-4242-8bf8-79b48623dab9)

**Comment by dedouwe26** [comment]
Hi @thecheesman1 
Can you show the build output?
There maybe is a build error.
Btw, in the bin folder, is there another folder called Release?

**Comment by thecheesman1** [comment]
no there's not a release folder and wheres the build out put is it this? 
![image](https://github.com/dedouwe26/Cosmetx/assets/174196056/f399ee31-009a-4b2b-a977-6ed82ca36b21)

![image](https://github.com/dedouwe26/Cosmetx/assets/174196056/c6fbf6a7-3468-4621-8450-2747a377f9c8)

**Comment by dedouwe26** [comment]
Did you use dotnet build or dotnet publish, because it is probably in there
