### ISSUE TITLE
HOW DO I BUILD THE MOD

### ISSUE THREAD

**Issue by Blueleafvr** [dedouwe26/Cosmetx#20]
ive tried everything and nothing works

**Comment by Blueleafvr** [comment]
THERE IS LIKE 89 Warnings AND 27 ERRORS??????????

**Comment by dedouwe26** [comment]
Please dont spam a issue: duplicate: #21

**Comment by dedouwe26** [comment]
What are the errors?

**Comment by dedouwe26** [comment]
see #22
