### ISSUE TITLE
hello, ever since this new update came out recently, cosmetx shows i have cosmetics, but i cannot see other peoples cosmetics including my ones , are you updating the mod? or is this only happening for me, i can see my cosmetics in the wardrobe though.

### ISSUE THREAD

**Issue by GKVR319** [dedouwe26/Cosmetx#22]

**Comment by dedouwe26** [comment]
Maybe i will fix it. Probably not, because this is there way of getting paid. So if everyone downloads this mod, no one will buy their currency.

**Comment by dedouwe26** [comment]
The fix the issue that you cant see your own cosmetics, simply remove the mod.

**Comment by GKVR319** [comment]
will this problem be fixed?? this mod helps me so much with youtube videos.

**Comment by therealbananaVR** [comment]
Please at least try to fix it, a bunch of people still use the **Cosmetx mod** till this day for vids. It's just too fun! We simply need this mod back and running so that everyone can enjoy it again.

**Comment by alexrednaz** [comment]
> Maybe i will fix it. Probably not, because this is there way of getting paid. So if everyone downloads this mod, no one will buy their currency.

If you're losing sleep over the financial repercussions this mod is having on Gorilla Tags annual revenue, then id say just let it die.
It was great while it lasted and we appreciate the effort put in to keep it working all this time.
If there is a C&D then nobody would blame you for sure.

**Comment by GKVR319** [comment]
we would respect your legacy in these mods that help us alot,but if you really cannot,you can abandon the mod. but thank you so much for making this,you dont know how many videos i posted with it. but we would highly appreciate it if you would come back, but all your desicion.

**Comment by GKVR319** [comment]
> > Maybe i will fix it. Probably not, because this is there way of getting paid. So if everyone downloads this mod, no one will buy their currency.
> 
> If you're losing sleep over the financial repercussions this mod is having on Gorilla Tags annual revenue, then id say just let it die. It was great while it lasted and we appreciate the effort put in to keep it working all this time. If there is a C&D then nobody would blame you for sure.

i agree

**Comment by dedouwe26** [comment]
Thanks! For everyone that supported this little mod, we have hit more than 10,000 VIEWS! For everyone that still wants a new update, there is a small chance that there will be one. Anyways, thanks alot!

**Comment by GKVR319** [comment]
> Thanks! For everyone that supported this little mod, we have hit more than 10,000 VIEWS! For everyone that still wants a new update, there is a small chance that there will be one. Anyways, thanks alot!

youre welcome :)
