### ISSUE TITLE
Building doesn't work

### ISSUE THREAD

**Issue by BucketofWater1** [dedouwe26/Cosmetx#23]
so uh, i downloaded the source code, extracted it then i did all the other steps and when i typed in dotnet build nothing happened.

**Comment by MrModdd** [comment]
the dll wasn't there and when i tried again i got a bunch of warnings and errors.

**Comment by dedouwe26** [comment]
What are the errors and warnings?
PS: This mod probably doesn't work anymore.

**Comment by MrModdd** [comment]
> What are the errors and warnings? PS: This mod probably doesn't work anymore.

They are mostly about the directory even though i did all of that and its still giving me errors and warnings

**Comment by MrModdd** [comment]
whoops

**Comment by dedouwe26** [comment]
Can you specify the errors?

**Comment by thecheesman1** [comment]
@dedouwe26 can you fix the mod?

**Comment by BucketofWater1** [comment]
> Can you specify the errors? @BucketofWater1

![Screenshot 2024-08-17 141743](https://github.com/user-attachments/assets/390af64b-9f08-447e-9030-2418af3d811e)

**Comment by dedouwe26** [comment]
> mod?

Maybe

**Comment by dedouwe26** [comment]
> > Can you specify the errors? @BucketofWater1
> 
> 
> 
> ![Screenshot 2024-08-17 141743](https://github.com/user-attachments/assets/390af64b-9f08-447e-9030-2418af3d811e)
> 
> 

What version of .NET u use

**Comment by dedouwe26** [comment]
Close as @BucketofWater1 is not responding
