### ISSUE TITLE
DnSpy and GTag

### ISSUE THREAD

**Issue by mganelli6684** [dedouwe26/Cosmetx#24]
Have DnSpy and have compiled but I believe, I'm missing the below step.

Which file do I open in DnSpy to find this entry? Or if I'm supposed to add the
below entry, which file do I insert it in and where?

Thanks

_In DnSpy you can find out where the cosmetics are handled.
So in GorillaNetworking.CosmeticsController.GetUserCosmeticsAllowed() you can apply a patch that gives you all cosmetics._

**Comment by dedouwe26** [comment]
Hello, you don't have to do this. The mod does it for you, but the mod will not be maintained for now, so it may not work.
