### ISSUE TITLE
piracy

### ISSUE THREAD

**Issue by jusnash** [dedouwe26/Cosmetx#4]
hello.
this mod is against the law
do not use it unless you want a quick trip to jail

**Comment by dedouwe26** [comment]
It's **client side only** so no body will notice.

**Comment by jusnash** [comment]
still against the law

**Comment by dedouwe26** [comment]
In the matter at hand, it is imperative to duly acknowledge the inherent complexities and multifaceted nuances surrounding the subject matter herein. It behooves all parties involved to appreciate the intricate tapestry woven by the intricate threads of legal jurisprudence, wherein the contours of legal discourse are navigated with meticulous precision.

Preliminary examination reveals a landscape characterized by an abundance of legal subtleties and an assortment of potential considerations that might arguably pertain to the matter at issue. It is incumbent upon us to engage in a thorough exploration of the intricacies, nuances, and idiosyncrasies that may potentially underpin the focal point of this particular discourse.

It is with due diligence that we undertake the deliberate and conscientious elucidation of the prevailing circumstances, all while maintaining a judicious awareness of the surrounding legal milieu. This, of course, necessitates a careful and considered perusal of the relevant statutes, jurisprudential authorities, and any other pertinent legal materials that may, in the fullness of time, come to bear upon the issue at hand.

In summation, it is the fervent recommendation of this discourse that the interested parties, in their respective capacities, engage in a sustained and concerted effort to foster a more profound understanding of the matter, with due consideration given to the labyrinthine nature of legal intricacies that may, in due course, manifest in a more comprehensive elucidation of the subject matter under scrutiny. -ChatGPT

**Comment by saerio** [comment]
you wont go to jail. its most likely a seace and desist against the dev.
