### ISSUE TITLE
Cosmetx mod not working

### ISSUE THREAD

**Issue by therealbananaVR** [dedouwe26/Cosmetx#8]
The **Cosmetx** mod has stopped working last week. Are there really any signs that the developer is aware of fixing this issue? If dedouwe26 sees this, just please comment so we can know that you're aware and fixing this problem. There hasn't been any comments by the official developer of the **Cosmetx** mod and I'm just worried he might've stopped looking forward to the mod.

**Comment by SigmaMan69420** [comment]
it doesn't work for me either I think the mod has to be recoded

**Comment by dedouwe26** [comment]
I can fix it, but I won't. Even if I would, I will not publish a new build of Cosmetx. 
I hope you understand why I won't publish a new build of Cosmetx. If I fix it, you can make the DLL file yourself.

**Comment by therealbananaVR** [comment]
Aww man. I guess it's fine. I'll just use my main acc for my cosmetics. I can't build my own DLL file since idk how to, so in that case i'll switch to normal Gorilla Tag.
