### ISSUE TITLE
i can't find dotnet build

### ISSUE THREAD

**Issue by mangoking189** [dedouwe26/Cosmetx#9]

**Comment by SigmaMan69420** [comment]
same

**Comment by alexrednaz** [comment]
You have to install .net onto your PC first, then you can run the commands in your terminal. be sure to navigate to the directory his source code is cloned in.
https://dotnet.microsoft.com/en-us/download

**Comment by dedouwe26** [comment]
I use the [dotnet 8.0](https://dotnet.microsoft.com/en-us/download/dotnet/8.0), that works.
